## Single Value Replacement

* Datasets often represent missing values using special placeholder numbers (such as `-99999`)
* `df.replace(old_value, new_value)` converts these placeholders to `NaN` or any valid replacement value

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('../datasets/nyc_weather_data.csv')
new_df = df.replace(-99999,np.nan)
new_df


,day,temperature,windspeed,event
0,1/1/2017,32,6.0,Rain
1,1/2/2017,-99999,7.0,Sunny
2,1/3/2017,28,NaN,Snow
3,1/4/2017,-99999,7.0,0
4,1/5/2017,32f,NaN,Rain
5,1/6/2017,31,-88888.0,Sunny
6,1/6/2017,34,5.0,0


## List Replacement — Handling Multiple Placeholders Simultaneously

* If a dataset uses multiple special placeholder values (e.g., `-99999`, `-88888`) to represent missing data, pass them as a list to convert all of them to `NaN` at once: `df.replace([-99999, -88888], np.nan)`

In [ ]:
new_df = df.replace([-99999,-88888],np.nan)
new_df

## Dictionary — Column-Specific Replacement

* Allows defining distinct "invalid values" for individual columns
* Real-world use case: `-99999` is invalid for numeric columns like `temperature` or `windspeed`, whereas `'0'` is invalid for text/categorical columns like `event`

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('datasets/nyc_weather_data.csv')
new_df = df.replace({
    'temperature' : -99999,
    'windspeed' : -99999,
    'event' : '0'
}, np.nan)
new_df

## Dictionary — Value-to-Value Mapping (Global Replacement)

* Maps specific existing values to new target values across the entire DataFrame (`{old_value: new_value}`) without specifying column names
* Replaces matching values wherever they appear across all columns (e.g., `df.replace({'No Event': 'None', -999: np.nan})`)

In [ ]:
new_df = df.replace({
    -99999 : np.nan,
    -88888 : np.nan,
    '0' : 'Sunny'
})
new_df

## Regex (Regular Expression) Replacement

* `regex=True` is required — ensures Pandas evaluates the target string as a pattern rule rather than literal text
* `[A-Za-z]` → Matches any English letter (uppercase or lowercase)
* **CRITICAL MISTAKE TO AVOID:** Writing `[A-za-z]` (capital `A` to lowercase `z`) is incorrect
* In ASCII encoding, special characters (`[`, `\`, `]`, `^`, `_`, ```) sit between uppercase `Z` and lowercase `a`, which will inadvertently match non-alphabetic characters
* Always use `[A-Za-z]` (separate uppercase and lowercase ranges)

In [ ]:
new_df = df.replace({
    'temperature' : '[A-Za-z]',
    'windspeed' : '[A-Za-z]',
},'',regex=True)
new_df

## List-to-List Replacement — Converting Categorical Data to Numeric

* Performs position-wise mapping: the first item in the target list is replaced by the first item in the replacement list, the second by the second, and so on
* Real-world / Machine Learning use case: Converting ordinal categorical ratings (e.g., `['Poor', 'Average', 'Good', 'Exceptional']`) into numerical scores (e.g., `[1, 2, 3, 4]`) for model inputs

In [ ]:
pd.set_option('future.no_silent_downcasting', True)
df = pd.DataFrame({
    'Score' : ['Good','Poor','Average','Exceptional','Good'],
   'Student' : ['Rohny','Monkesh','Rajni','Ayush','Pari']
})
new_df = df.replace(['Exceptional','Good','Average','Poor'],[90,70,60,40])
new_df

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Amit", "Rahul", "Priya", "Neha"],
    "Marks": [90, -99999, 80, -88888],
    "Grade": ["A", "0", "B", "0"]
})
new_df = df.replace({
    -99999 : np.nan,
    -88888 : np.nan,
    '0' : np.nan
})
new_df = new_df.fillna(50)
new_df